### ISSUE TITLE
Move this repo to nrf-rs

### ISSUE THREAD

**Issue by jamesmunns** [nrf-rs/nrf52810-pac#1]
Hey @chocol4te, let's figure out the best way to move this repo to the `nrf-rs` organization!

I think there are two ways to do this:

* You can make me an admin of this repo, and I can transfer it to the nrf-rs organization, and keep you as an admin
* I can add you as a member of the nrf-rs organization, and you can transfer it there.

For the second option, it might take a couple days so I can get a :+1: from the other nrf-rs admins to add you to the team, and you will need 2FA enabled on your github account. Let me know if you have a preference!

**Comment by fmckeogh** [comment]
I've sent you an invite for this repo :)

I'd definitely like to be more involved in using Rust on nRF devices and I'd love to be a member, but I'm not sure I can really make a solid time commitment right now. I'll of course maintain my contributions and hopefully work on other things, but I wouldn't want to agree to join and then cause issues.

**Comment by jamesmunns** [comment]
Hey! I got the invite! I think you need to make me an admin/owner before I can transfer the repo

**Comment by fmckeogh** [comment]
I couldn't make you anything higher than a collaborator, I thought transferring might be easier :)

**Comment by jamesmunns** [comment]
Oops, I forgot that you probably could have just transferred here directly. Oh well, thanks for helping out with that, the repo is now in the right place!
