### ISSUE TITLE
Make nrf52 team a crates.io owner

### ISSUE THREAD

**Issue by jamesmunns** [nrf-rs/nrf52810-pac#5]
CC @chocol4te

**Comment by jamesmunns** [comment]
The way to do this is to cd to the crate, then run

```
cargo owner --add github:nrf-rs:nrf52
```

**Comment by fmckeogh** [comment]
```
error: failed to invite owners to crate nrf52810-pac: api errors (status 200 OK): It looks like you don't have permission to query a necessary property from Github to complete this request. You may need to re-authenticate on crates.io to grant permission to read github org memberships. Just go to https://crates.io/login
```

But when I go to https://crates.io/login, it redirects me to GitHub, then back to crates.io, but I am shown this page:
![Screenshot 2019-04-24 at 11 43 56](https://user-images.githubusercontent.com/8290136/56649881-432a3080-6686-11e9-961a-59812ad9041e.png)

Even though if I just go to crates.io in a new tab, I am already logged into crates.io.

**Comment by fmckeogh** [comment]
I've manually sent a request, did it work?

**Comment by jamesmunns** [comment]
@chocol4te, no, unfortunately not. Perhaps try logging in from another browser (or incognito window?) Or maybe removing and re-adding crates.io oauth from github?

**Comment by fmckeogh** [comment]
@jamesmunns  https://github.com/rust-lang/crates.io/issues/1446#issuecomment-401352211

I need to be a member to add a team

**Comment by jamesmunns** [comment]
@chocol4te invited :)
